
  
INSERT INTO USER( UID,FIRST_NAME, LAST_NAME, EMAIL_ID,PASSWORD,PASSWORD_HINT) 
VALUES(1,'Anita','Devdare','anuadevdare@gmail.com',('string'),'test');
INSERT INTO USER( UID,FIRST_NAME, LAST_NAME, EMAIL_ID,PASSWORD,PASSWORD_HINT) 
VALUES(2,'Smita','Devdare','smitudevdare@gmail.com',('sim123'),'nikname');
INSERT INTO USER( UID,FIRST_NAME, LAST_NAME, EMAIL_ID,PASSWORD,PASSWORD_HINT) 
VALUES(3,'Prajakta','Devdare','prajadevdare@gmail.com',('praj123'),'nikname');
INSERT INTO USER( UID,FIRST_NAME, LAST_NAME, EMAIL_ID,PASSWORD,PASSWORD_HINT) 
VALUES(4,'Ram','Devdare','ramadevdare@gmail.com',('ram123'),'nikname');
INSERT INTO USER( UID,FIRST_NAME, LAST_NAME, EMAIL_ID,PASSWORD,PASSWORD_HINT) 
VALUES(5,'Lakhan','Devdare','lakhanadevdare@gmail.com',('laku123'),'nikname');


INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(1,1,'pen','Grocery','pen for employee',1000,'2017-03-15');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(2,1,'Electricity bill','Electricity','Electricity',10000,'2019-03-15');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(3,2,'Internet bill','Internet','Internet bill',100,'2019-04-14');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(4,2,'Food for client','Food','Food for client',100,'2019-04-14');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(5,3,'Phone bill','Phone','Phone bill',100,'2019-02-14');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(6,3,'pen','Grocery','pen for employee',1000,'2017-09-15');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(7,4,'Electricity bill','Electricity','Electricity',10000,'2019-01-15');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(8,4,'Internet bill','Internet','Internet bill',100,'2019-06-14');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(9,5,'Food for client','Food','Food for client',100,'2019-05-14');
INSERT INTO EXPENSE( EID,USER_ID,EXPENSE_TITLE, EXPENSE_CATEGORY, EXPENSE_DESCRIPTION,EXPENSE_AMOUNT,EXPENSE_DATE) 
VALUES(10,5,'Phone bill','Phone','Phone bill',100,'2019-05-14');
